### ISSUE TITLE
 Portfolio-Website Andres Cantillo

### ISSUE THREAD

**Issue by David-Verde** [Zeraltz/Portfolio-Website#3]
kindly add alt content to the <img> element, for people with disabilities.

you could create different sections for every element in the project. for the semantic purpose, it is a lot easier to separate the elements into sections

kindly add a . before / on the <img> element, so the link becomes a relative one and it cannot be broken when you copy and paste the whole project

**Comment by Andyveloper** [comment]
Thanks a lot for your input, I'll be working on the suggested changes
